# Author: Dustin Brothers
# Description:
#   yaml playbook to setup a RPi Macintosh Emulation system
---
- hosts: all
  tasks:
    # The Low Memory setup could still be needed...
    - include_tasks: ./support/nodesktop_setup.yml
    - include_tasks: ./support/lowmem_setup.yml
    - include_tasks: ./support/base_setup.yml
    - include_tasks: ./support/waveshare2p8inDPI_setup.yml
    - include_tasks: ./support/basiliskii_setup.yml

    ############################################################################
    # Reboot after all setup is complete...
    - name: Reboot to finalize installations and updates...
      reboot:
        msg: "Rebooting machine..."
      become: true
